import Wrapper from '@/components/Wrapper';
import { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
export const metadata: Metadata = {
  title: 'TAN Blog',
  description: 'Generated by create next app',
};
const Blog = () => {
  return (
    <Wrapper>
      <section className="m-8  text-gray-600  lg:flex lg:gap-8">
        <div className="flex flex-col gap-3 lg:w-2/3">
          <Image
            alt="tan ecowas new"
            src="/news/ecowas.jpg"
            width={200}
            height={200}
          />
          <h1>THE ECOWAS COMMON EXTERNAL TARIFF (CET) 2022 EDITION</h1>
          <h2> ECOWAS Updates Common External Tariff Nomenclature</h2>

          <p>
            ECOWAS has made substantial revisions to its Tariff and Statistical
            Nomenclature (TSN) within the ECOWAS Common External Tariff (CET) to
            bolster trade operations and comply with global norms. This
            adjustment aligns with the World Customs Organization's (WCO) 2022
            Harmonized System (HS), a pivotal step towards smoother trade
            processes within the region. The CET, acting as a vital trade
            framework, aims to diminish trade barriers, boost economic
            integration, and elevate the competitiveness of ECOWAS member states
            on the global stage by harmonizing tariff classifications and
            statistical nomenclature.
          </p>
          <p>
            The update's significance lies in its adherence to the WCO's 2022 HS
            version, a widely recognized system for classifying globally traded
            goods. This alignment ensures consistency with international
            standards, simplifies customs procedures, reduces administrative
            complexities, and enhances transparency in trade regulations. This
            harmonization not only fosters seamless trade within ECOWAS but also
            facilitates accurate data collection, aids informed policy-making,
            and improves supply chain efficiency, reinforcing ECOWAS' commitment
            to modernizing trade practices and fostering regional economic
            growth.
          </p>

          <p>
            In conclusion, the recent update to the Tariff and Statistical
            Nomenclature of the ECOWAS Common External Tariff represents a
            significant stride towards enhancing trade efficiency, harmonizing
            trade practices, and aligning with global standards. By embracing
            these changes, ECOWAS reaffirms its commitment to fostering a
            conducive environment for trade and economic development in West
            Africa and beyond.
          </p>
        </div>
        <div className="mt-4 bg-gray-100 p-3">
          <h1 className="text-2xl font-bold">Latest News</h1>
          <ul className="divide-y divide-gray-900 pt-5 font-semibold">
            <li className="pt-5 ">
              <Link href="/blogs/blog-2">Export and Import of good act</Link>
            </li>
            <li className="pt-5 ">
              <Link href="/blogs/blog-3">
                What are Import Tariffs in Ghana?
              </Link>
            </li>
            <li className=" pt-5">
              <Link href="#">6 ways to select a freight service provider.</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">Economics impact on global shipping.</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">How to ensure effective documentations.</Link>
            </li>
            {/* <li className=" pt-5">
            <Link href="#">Germany decisions on global freight service</Link>
          </li> */}
            {/* <li className=" pt-5">
            <Link href="#">
              Ghana Freight providers and stakeholders meeting.
            </Link>
          </li> */}
            <li></li>
          </ul>
        </div>
      </section>
    </Wrapper>
  );
};

export default Blog;
