import Wrapper from '@/components/Wrapper';
import { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
export const metadata: Metadata = {
  title: 'TAN Blog',
  description: 'Generated by create next app',
};
const Blog = () => {
  return (
    <Wrapper>
      <section className="m-8  text-gray-600  lg:flex lg:gap-8">
        <div className="flex flex-col gap-3 lg:w-2/3">
          <Image
            alt="tan ecowas new"
            src="/news/exportact.jpg"
            width={400}
            height={300}
          />
          <h1 className="text-xl font-bold capitalize lg:text-3xl">
            Export and Import of good act
          </h1>
          {/* <h2> ECOWAS Updates Common External Tariff Nomenclature</h2> */}

          <p>
            When it comes to freight services, it’s crucial to understand the
            nuances of exporting goods with restrictions. These restrictions may
            stem from international regulations or Ghana’s specific trade
            policies. Whether it’s limitations on quantities or adherence to
            particular specifications, these guidelines are non-negotiable. To
            navigate this terrain, obtaining the necessary permits or
            certificates is a prerequisite for handling any restricted
            commodities in the export process.
          </p>
          <p>
            For both traditional and non-traditional export goods, compliance
            with export restrictions remains paramount. This includes a
            meticulous approach to documentation and adherence to established
            protocols. By ensuring that each shipment meets the required
            standards, freight services can maintain smooth operations while
            upholding legal and regulatory obligations. The ability to export
            restricted goods hinges on meticulous planning and adherence to the
            prescribed guidelines.
          </p>

          <p>
            In the realm of freight services, understanding and adhering to
            export restrictions is a cornerstone of responsible and efficient
            logistics. From navigating international laws to complying with
            Ghana's trade policies, every step in the export process demands
            precision and diligence. By obtaining the requisite permits and
            certificates and staying abreast of evolving regulations, freight
            services can uphold their commitment to seamless and compliant cargo
            transport, be it traditional or non-traditional exports.
          </p>
        </div>
        <div className="mt-4 bg-gray-100 p-3">
          <h1 className="text-2xl font-bold">Latest News</h1>
          <ul className="divide-y divide-gray-900 pt-5 font-semibold">
            <li className="pt-5 ">
              <Link href="/blogs/blog-1">
                {' '}
                The ECOWAS common external tariff (CET) 2022 edition
              </Link>
            </li>
            <li className="pt-5 ">
              <Link href="/blogs/blog-3">
                What are Import Tariffs in Ghana?
              </Link>
            </li>
            {/* <li className="pt-5 ">
            <Link href="#">Global freight Forwarders Initiatives.</Link>
          </li> */}
            <li className=" pt-5">
              <Link href="#">6 ways to select a freight service provider.</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">Economics impact on global shipping.</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">How to ensure effective documentations.</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">Germany decisions on global freight service</Link>
            </li>
            {/* <li className=" pt-5">
            <Link href="#">
              Ghana Freight providers and stakeholders meeting.
            </Link>
          </li> */}
            <li></li>
          </ul>
        </div>
      </section>
    </Wrapper>
  );
};

export default Blog;
