import Wrapper from '@/components/Wrapper';
import { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
export const metadata: Metadata = {
  title: 'TAN Blog',
  description: 'Generated by create next app',
};
const Blog = () => {
  return (
    <Wrapper>
      <section className="m-8  text-gray-600  lg:flex lg:gap-8">
        <div className="flex flex-col gap-3 lg:w-2/3">
          <Image
            alt="tan ecowas new"
            src="/news/importt.jpg"
            width={400}
            height={200}
          />
          <h1 className="text-xl font-bold capitalize lg:text-3xl">
            What are Import Tariffs in Ghana?
          </h1>
          {/* <h2> ECOWAS Updates Common External Tariff Nomenclature</h2> */}

          <p>
            In the realm of freight services within Ghana, the Harmonized System
            (HS Code) is the prevailing classification method for goods. This
            system categorizes goods comprehensively, allowing for streamlined
            customs procedures. However, it's important to note that nearly all
            goods, unless they fall under specific exemptions from customs
            duties, are subject to import duties, Value Added Tax (VAT), and
            additional fees and charges. These charges collectively contribute
            to the overall cost of importing goods into the country.
          </p>
          <p>
            The import duty is primarily calculated based on the Cost Insurance
            Freight (CIF) value of the goods. This value encompasses the cost of
            the goods, insurance, and freight charges. In addition to the import
            duty, VAT and other associated fees are calculated based on the sum
            of CIF plus the duty amount. This comprehensive approach ensures
            that all relevant costs and taxes are accounted for, providing a
            clear and standardized framework for importers and freight service
            providers alike.
          </p>

          <p>
            For stakeholders in the freight industry, understanding and
            accurately assessing these charges are essential components of
            efficient logistics management. By comprehensively evaluating the
            CIF value, import duties, VAT, and associated fees, freight service
            providers can ensure transparent and compliant import processes.
            This adherence to regulatory frameworks not only facilitates
            smoother customs clearance but also contributes to the overall
            reliability and professionalism of freight services operating within
            Ghana's import landscape.
          </p>
        </div>
        <div className="mt-4 bg-gray-100 p-3">
          <h1 className="text-2xl font-bold">Latest News</h1>
          <ul className="divide-y divide-gray-900 pt-5 font-semibold">
            <li className="pt-5 ">
              <Link href="/blogs/blog-1">
                The ECOWAS common external tariff (CET) 2022 edition
              </Link>
            </li>
            <li className="pt-5 ">
              <Link href="/blogs/blog-2">Export and Import of good act</Link>
            </li>
            {/* <li className="pt-5 ">
            <Link href="#">Global freight Forwarders Initiatives.</Link>
          </li>
          <li className=" pt-5">
            <Link href="#">6 ways to select a freight service provider.</Link>
          </li> */}
            <li className=" pt-5">
              <Link href="#">Economics impact on global shipping.</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">How to ensure effective documentations.</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">Germany decisions on global freight service</Link>
            </li>
            <li className=" pt-5">
              <Link href="#">
                Ghana Freight providers and stakeholders meeting.
              </Link>
            </li>
            <li></li>
          </ul>
        </div>
      </section>
    </Wrapper>
  );
};

export default Blog;
